/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Entrada1 extends javax.swing.JFrame {
    /**
     * Creates new form Entrada1
     */
    public static int n,m;
  
    public Entrada1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(580, 310);
        this.panel.setSize(580, 310);
        this.panel.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labeltitulo = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        tfvariables = new javax.swing.JTextField();
        tfrestricciones = new javax.swing.JTextField();
        botonregresar = new javax.swing.JButton();
        botonaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(580, 310));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltitulo.setText("Modelo de Programación Lineal");
        panel.add(labeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("Ingrese la cantidad de restricciones:");
        panel.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("Ingrese la cantidad de variables de decisión:");
        panel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        tfvariables.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfvariables.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfvariablesKeyTyped(evt);
            }
        });
        panel.add(tfvariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 30, -1));

        tfrestricciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfrestricciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfrestriccionesKeyTyped(evt);
            }
        });
        panel.add(tfrestricciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 30, -1));

        botonregresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonregresar.setText("Regresar");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });
        panel.add(botonregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 100, 30));

        botonaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonaceptar.setText("Aceptar");
        botonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaceptarActionPerformed(evt);
            }
        });
        panel.add(botonaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, 30));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfvariablesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfvariablesKeyTyped
        // TODO add your handling code here:
        int tama = tfvariables.getText().length();
        if(tama==2){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if(!(c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_tfvariablesKeyTyped

    private void tfrestriccionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrestriccionesKeyTyped
        // TODO add your handling code here:
        int tama = tfrestricciones.getText().length();
        if(tama==2){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if(!(c >= '0' && c <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_tfrestriccionesKeyTyped

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_botonregresarActionPerformed

    private void botonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaceptarActionPerformed
        // TODO add your handling code here:
        String variables = tfvariables.getText(), restricciones = tfrestricciones.getText();
        if(variables.equals("") || (restricciones.equals(""))){
            JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos solicitados", "Error", 0);
        }else{
            n = Integer.parseInt(variables);
            m = Integer.parseInt(restricciones);
            this.setVisible(false);
            new Entrada2().setVisible(true);
        }
        
    }//GEN-LAST:event_botonaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonaceptar;
    private javax.swing.JButton botonregresar;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tfrestricciones;
    public static javax.swing.JTextField tfvariables;
    // End of variables declaration//GEN-END:variables
}
