/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Eduardo
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setSize(800, 720);
        this.panel.setSize(800,720);
        this.panel.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labellogo = new javax.swing.JLabel();
        membretel1 = new javax.swing.JLabel();
        membretel2 = new javax.swing.JLabel();
        membretel3 = new javax.swing.JLabel();
        membretel4 = new javax.swing.JLabel();
        membretel6 = new javax.swing.JLabel();
        membretel7 = new javax.swing.JLabel();
        membretel8 = new javax.swing.JLabel();
        membretel5 = new javax.swing.JLabel();
        membretel9 = new javax.swing.JLabel();
        membretel10 = new javax.swing.JLabel();
        membretel11 = new javax.swing.JLabel();
        membretel12 = new javax.swing.JLabel();
        membretel13 = new javax.swing.JLabel();
        botoncontinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(790, 780));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpg"))); // NOI18N
        panel.add(labellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        membretel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel1.setText("Universidad de Oriente");
        panel.add(membretel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        membretel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel2.setText("Núcleo Nueva Esparta");
        panel.add(membretel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        membretel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel3.setText("Escuela de Ingeniería y Ciencias Aplicadas");
        panel.add(membretel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        membretel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel4.setText("Licenciatura en Informática");
        panel.add(membretel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        membretel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel6.setText("Integrantes:");
        panel.add(membretel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        membretel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel7.setText("Resolución de problemas de asignación de recursos a través de un modelo de programación lineal");
        panel.add(membretel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        membretel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel8.setText("haciendo uso del Método Simplex o de la Técnica de penalización.");
        panel.add(membretel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        membretel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel5.setText("Programación Lineal");
        panel.add(membretel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        membretel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        membretel9.setText("Eduardo Rodríguez C.I. 26.082.457");
        panel.add(membretel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        membretel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel10.setText("Integrantes:");
        panel.add(membretel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        membretel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        membretel11.setText("Profesora:");
        panel.add(membretel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        membretel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        membretel12.setText("Ing. Eyamir Ugueto");
        panel.add(membretel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        membretel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        membretel13.setText("Andrés Luna C.I. 25.999.071");
        panel.add(membretel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        botoncontinuar.setBackground(new java.awt.Color(204, 204, 204));
        botoncontinuar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botoncontinuar.setText("Iniciar");
        botoncontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncontinuarActionPerformed(evt);
            }
        });
        panel.add(botoncontinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 110, 30));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncontinuarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Entrada1().setVisible(true);
        
    }//GEN-LAST:event_botoncontinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncontinuar;
    private javax.swing.JLabel labellogo;
    private javax.swing.JLabel membretel1;
    private javax.swing.JLabel membretel10;
    private javax.swing.JLabel membretel11;
    private javax.swing.JLabel membretel12;
    private javax.swing.JLabel membretel13;
    private javax.swing.JLabel membretel2;
    private javax.swing.JLabel membretel3;
    private javax.swing.JLabel membretel4;
    private javax.swing.JLabel membretel5;
    private javax.swing.JLabel membretel6;
    private javax.swing.JLabel membretel7;
    private javax.swing.JLabel membretel8;
    private javax.swing.JLabel membretel9;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
