/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.DecimalFormat;

/**
 *
 * @author Eduardo
 */
public class Salida extends javax.swing.JFrame {
    public double[][][] matrices;
    public String[] columnas;
    public DefaultTableModel modelo;
    /**
     * Creates new form Salida
     */
    public Salida() {
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        DecimalFormat formateador = new DecimalFormat("####.##");
        double[] valores = new double[Ventanas.Entrada2.tabla_optima.length];
        int i=0;
        for (double[] tabla_optima : Ventanas.Entrada2.tabla_optima) {
            valores[i] = tabla_optima[tabla_optima.length-1];
            i++;
        }
        JLabel f = new JLabel();
        f.setFont(new java.awt.Font("Tahoma", 0, 14));
        f.setText("Z = "+valores[0]+" ");
        panel.add(f);
        int j=1;
        for (String var_basica : Ventanas.Entrada2.var_basicas) {
            JLabel var = new JLabel();
            var.setFont(new java.awt.Font("Tahoma", 0, 14));
            var.setText(var_basica);
            panel.add(var);
            JLabel num = new JLabel();
            num.setFont(new java.awt.Font("Tahoma", 0, 14));
            num.setText(" = "+formateador.format(valores[j])+" ");
            panel.add(num);
            j++;
        }
        
        //A partir de aqui empieza la fumada de lumpia para permitir ver todas las iteraciones.
        String[] columnas = new String[Ventanas.Entrada2.variables.length+1];
        int k;
        for (k = 0; k < Ventanas.Entrada2.variables.length; k++) {
            columnas[k] = Ventanas.Entrada2.variables[k];
                       
        }
        columnas[k] = "<html><p>Sol</p></html>";
        modelo = new DefaultTableModel(null,columnas);
        Iterator<double[][]> it = Ventanas.Entrada2.iteraciones.iterator();
        
        int x=Ventanas.Entrada2.iteraciones.size();
        
                
        String[] numerosIt= new String[x];
        for (int kj = 1; kj <= x; kj++) {
            numerosIt[kj-1] = String.valueOf(kj);
        }
        iteracionesBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        iteracionesBox.setModel(new javax.swing.DefaultComboBoxModel(numerosIt));
        
        matrices = new double[x][Ventanas.Entrada2.tabla_optima.length][Ventanas.Entrada2.tabla_optima[0].length];
        
        x=0;
        while(it.hasNext()){
            matrices[x] = it.next();
            x++;
        }
        
        String fila[] = new String[columnas.length];
        for (int kj = 0; kj < Ventanas.Entrada2.tabla_optima.length; kj++) {
            fila = new String[columnas.length];
            for (int l = 0; l < Ventanas.Entrada2.tabla_optima[0].length; l++) {
                fila[l] = formateador.format(Ventanas.Entrada2.tabla_optima[kj][l]);
            }
            modelo.addRow(fila);
            
        }
        tabla.setModel(modelo);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        botonregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        scrollpane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        iteracionesBox = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        veriteracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        scrollpane.setViewportView(panel);

        panelprincipal.add(scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 440, 50));

        botonregresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonregresar.setText("Regresar");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });
        panelprincipal.add(botonregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Solución:");
        panelprincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        labeltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltitulo.setText("Modelo de Programación Lineal");
        panelprincipal.add(labeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpane2.setViewportView(tabla);

        panelprincipal.add(scrollpane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 470, 110));

        panelprincipal.add(iteracionesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Iteración:");
        panelprincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        veriteracion.setText("Ver iteración");
        veriteracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veriteracionActionPerformed(evt);
            }
        });
        panelprincipal.add(veriteracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        getContentPane().add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere ir a la pantalla anterior? Se perderán todos los cambios efectuados", "Atención", YES_NO_OPTION, QUESTION_MESSAGE);
        if(resp == JOptionPane.YES_OPTION){
            this.setVisible(false);
            //new Entrada2().setVisible(true);
            
        }

    }//GEN-LAST:event_botonregresarActionPerformed

    private void veriteracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veriteracionActionPerformed
        DecimalFormat formateador = new DecimalFormat("####.##");
        int iteracion =Integer.parseInt(iteracionesBox.getSelectedItem().toString());
        String[] columnas = new String[Ventanas.Entrada2.variables.length+1];
        int k;
        for (k = 0; k < Ventanas.Entrada2.variables.length; k++) {
            columnas[k] = Ventanas.Entrada2.variables[k];
                       
        }
        columnas[k] = "<html><p>Sol</p></html>";
        modelo = new DefaultTableModel(null,columnas);
        String fila[] = new String[Ventanas.Entrada2.variables.length+1];
        
        for (int kj = 0; kj < Ventanas.Entrada2.tabla_optima.length; kj++) {
            fila = new String[Ventanas.Entrada2.variables.length+1];
            for (int l = 0; l < Ventanas.Entrada2.tabla_optima[0].length; l++) {
                fila[l] = formateador.format(matrices[iteracion-1][kj][l]);
            }
            modelo.addRow(fila);
            
        }
        tabla.setModel(modelo);      // TODO add your handling code here:
    }//GEN-LAST:event_veriteracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonregresar;
    private javax.swing.JComboBox<String> iteracionesBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JTable tabla;
    private javax.swing.JButton veriteracion;
    // End of variables declaration//GEN-END:variables
}
