/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Eduardo
 */
public class SalidaArt extends javax.swing.JFrame {

    /**
     * Creates new form SalidaArt
     */
    public SalidaArt() {
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeltitulo1 = new javax.swing.JLabel();
        botonM = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        botonregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltitulo1.setText("Modelo de Programación Lineal");
        jPanel1.add(labeltitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 50));

        botonM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonM.setText("Tecnica M");
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        jPanel1.add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 30));

        boton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton2.setText("Método de 2 fases");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, 30));

        botonregresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonregresar.setText("Regresar");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
           new Salida().setVisible(true);    
// TODO add your handling code here:
    }//GEN-LAST:event_botonMActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
           new SalidaDosFases().setVisible(true);
    }//GEN-LAST:event_boton2ActionPerformed

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        // TODO add your handling code here:
        //int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere ir a la pantalla anterior? Se perderán todos los cambios efectuados", "Atención", YES_NO_OPTION, QUESTION_MESSAGE);
        //if(resp == JOptionPane.YES_OPTION){
            this.setVisible(false);
            //new Entrada2().setVisible(true);

        //}
    }//GEN-LAST:event_botonregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalidaArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalidaArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalidaArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalidaArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalidaArt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton2;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonregresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeltitulo1;
    // End of variables declaration//GEN-END:variables
}
